Client displays connection
KirillTregubov/Share pull request #2
Opened 2024-06-29 01:14 UTC by Jeffkw213

So I'm be honest I don't know if I did this correctly.

Can you take a look.

It might be the ugliest thing you've ever seen

working progress

2024-07-02 18:02 UTC, KirillTregubov requested changes

2024-07-02 18:02 UTC, KirillTregubov commented on server/index.ts
> +let user: { id: string }
We don't need this global variable

For future reference, you should have imported the User type from schemas to keep the definition centralized to one place

2024-07-02 18:02 UTC, KirillTregubov commented on server/index.ts
> +      user = UserSchema.parse({
This becomes `const user`

2024-07-02 18:02 UTC, KirillTregubov commented on server/index.ts
> +      //WHY IS IT SENDING THE MESSAGE and displaying it in the client. But atleast in the console it shows that the message was recieved
I was printing all messages on the frontend for debugging / to show how it worked. We should create a message formatting so that the client can discern the purposes of a message. (this should most likely take the form of an object with a type property that denotes if its for internal use, to show to a user, etc)

In this case, the message sent on the next line lets the client know it is successfully connected. Before this message, we have no such guarantee.

2024-07-02 18:02 UTC, KirillTregubov commented on server/index.ts
> +    async message(ws, message) {
You only need async if you are using the `await` keyword, or are returning a promise. In this case it's unnecessary

2024-07-03 03:44 UTC, Jeffkw213 commented on server/index.ts
> +      //WHY IS IT SENDING THE MESSAGE and displaying it in the client. But atleast in the console it shows that the message was recieved
colour coding messages:
for example,
blue = join
green = message sent
red = thanos snaped

2024-07-07 22:06 UTC, merged